# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c8f54738a8875dbc0cf0f1f25fb2c8a22966e14fe1f25c40220d8fbadc96242c00cfa7c325c0c975859177533d7d242c51db4ef98b0fa82d5857f365368e28b

test:
  secret_key_base: 932e982340751723c3b03a1defa218d49a5681eb950b5c1a6a165f0dd06a279d77292cd5aae3cbd558d6bd9a6fe4a0451c72d76497b1a0003cba5975859a9c4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
